project:
  type: website
  preview: 
      port: 3637

execute: 
  freeze: auto

website:
  title: "feidlambda"
  description: "Koleksi lambda oleh FIAKO Engineering"

  site-url: https://lambda.fiako.engineering
  repo-url: https://github.com/fiakoenjiniring/feidlambda
  repo-actions: [edit, issue]

  reader-mode: true
  search: 
    location: navbar
    type: textbox
  page-navigation: true


  # FOR TWITTER / open-graph
  image: "fiakologo.png"
  favicon: "fiakologo.png"

  ## NAVIGATION BAR
  navbar:
    title: false
    background: dark
    # foreground: warning
    # pinned: false

    collapse: true

    logo: "fiakologo.png"

    left:
      - text: Home
        href: index.qmd
      - text: Dokumentasi
        menu:
        - href: docs/penggunaan.qmd
        - href: docs/glossary.qmd
      - text: feidlambda 0.x
        menu:
        - href: release/feidlambda.qmd
        - href: release/feidlambda-0-2-0.qmd
        - href: release/feidlambda-0-1-0.qmd
      - text: Greenhorn
        menu:
        - text: "Greenhorn"
          href: greenhorn/index.qmd
        - text: feidlambda I
          href: greenhorn/index.qmd
          # href: greenhorn/feidlambda-2/presentation.qmd
        - text: feidlambda II
          href: greenhorn/feidlambda-2/index.qmd
        - text: feidlambda III
          href: greenhorn/index.qmd
          # href: release/feidlambda-0-1-0.qmd

        
    right:
      - icon: github
        href: https://github.com/fiakoenjiniring/feidlambda

  sidebar: 
    - id: side-docs
      style: floating
      contents:
        - section: "Dokumentasi"
          contents: 
            - href: docs/penggunaan.qmd
            - href: docs/glossary.qmd

    - id: side-feidlambda
      style: floating
      contents:
        - section: Basics
          contents:
            - "yoooo"
            - "aaaa"
    
    - id: side-feidlambda-2
      style: floating
      contents:
      - text: Pendahuluan
        href: greenhorn/feidlambda-2/index.qmd
      - text: Presentasi
        href: greenhorn/feidlambda-2/presentation.qmd
      - Review
      - section: Logical
        contents:
          - Fungsi Logical
          - Operator Logical
          - Fungsi IS*
      - section: Dynamic Array Formula
        contents:
          - FILTER, UNIQUE
          - RANDARRAY, SEQUENCE
          - SORT, SORTBY
          - XLOOKUP, XMATCH
      - section: Fungsi Baru
        contents:
          - CONCAT
          - IFS, MAXIFS, MINIFS
          - SWITCH
          - TEXTJOIN
          - LET
      - section: User Defined Lambda (UDL)
        contents:
          - Pengenalan LAMBDA
          - Menggabungkan LAMBDA dan LET
          - Advanced Formula Environment (AFE)
          - Berbagi UDL

  ## SIDEBAR
  page-footer:
    right: >-
      developed by **fiako**dev. 
      built with ❤️ and [Quarto](https://quarto.org/).
    left: >-
      &copy; 2022 PT. FIAKO ENJINIRING INDONESIA. 
      <a rel="license" target="_blank" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC-BY-NC-SA 4.0</a>.

format:
  html:
    theme: default # lux, materia, minty, sandstone, spacelab, yeti, zephyr
    css: styles.css
    toc: true



