project:
  type: website
  preview: 
      port: 3637

execute: 
  freeze: auto

website:
  title: "feidlambda"
  description: "Koleksi User Defined LAMBDA (UDL) oleh FIAKO Engineering"

  site-url: https://lambda.fiako.engineering
  repo-url: https://github.com/fiakoenjiniring/feidlambda
  repo-actions: [edit, issue]

  reader-mode: true
  search: 
    location: navbar
    type: textbox
  page-navigation: true


  # FOR TWITTER / open-graph
  image: /assets/original_feidlambda_logo.png
  favicon: /assets/original_feidlambda_logo.png

  ## NAVIGATION BAR
  navbar:
    title: FIAKO-FEIDLAMBDA
    background: dark
    # foreground: warning
    # pinned: false

    collapse: true

    logo: /assets/original_feidlambda_logo.png

    left:
      - text: Home
        href: index.qmd
      - text: feidlambda
        menu:
        - href: release/source-code.qmd
        - href: release/feidlambda-0-4.qmd
        - href: release/feidlambda-0-3.qmd
        - href: release/feidlambda-0-2-0.qmd
        - href: release/feidlambda-0-1-0.qmd
      - text: feid*
        menu:
        - href: release/feidmath-0-1.qmd
      - text: Dokumentasi
        menu:
        - href: docs/lambda-style-guide.qmd
        - href: docs/install.qmd
        - href: docs/glossary.qmd
      - text: Artikel
        menu:
        - href: article/migration-v0-2-to-v0-3.qmd
        
    right:
      - icon: github
        href: https://github.com/fiakoenjiniring/feidlambda

  sidebar: 
    - id: side-docs
      style: floating
      contents:
        - section: "Dokumentasi"
          contents: 
            - href: docs/install.qmd
            - href: docs/glossary.qmd

    - id: side-feidlambda
      style: floating
      contents:
        - section: Basics
          contents:
            - "yoooo"
            - "aaaa"
    
    - id: side-feidlambda-2
      style: floating
      contents:
      - text: Pendahuluan
        href: greenhorn/feidlambda-2/index.qmd
      - text: Presentasi
        href: greenhorn/feidlambda-2/presentation.qmd
      - Review Daftar Istilah
      - section: Explorasi tentang _Logical_
        contents:
          - Fungsi Logical
          - Logical dan Number
          - Fungsi `IS*`
      - section: _Dynamic Array Formula_ (DAF)
        contents:
          - Menyeleksi/memilih data
          - Membangkitkan data
          - Menyusun data
          - Mencari data
      - section: Fungsi Baru dari Excel 2019 dan 2021
        contents:
          - Penggabungan Teks
          - Koleksi `IF*`
      - section: User Defined _Lambda_ (UDL)
        contents:
          - LAMBDA dan UDL
          - Contoh
          - Pengembangan lebih lanjut

  ## SIDEBAR
  page-footer:
    right: >-
      developed by **fiako**dev
    left: >-
      &copy; 2022-2023 PT. FIAKO ENJINIRING INDONESIA

format:
  html:
    theme: journal # lux, materia, minty, sandstone, spacelab, yeti, zephyr
    css: styles.css
    toc: true
    link-external-newwindow: true



