project:
  type: website
  preview: 
      port: 3637

website:
  title: "feidlambda"
  description: "LAMBDAPROJECT by FIAKO ENGINEERING"

  site-url: https://dev.fiako.engineering/feidlambda
  repo-url: https://github.com/fiakoenjiniring/feidlambda

  reader-mode: true
  search: 
    location: sidebar
    type: textbox
  page-navigation: true


  # FOR TWITTER / open-graph
  image: "fiakologo.png"
  favicon: "fiakologo.png"

  ## NAVIGATION BAR
  navbar:
    title: false
    background: dark
    foreground: warning
    pinned: false

    collapse: true

    logo: "fiakologo.png"

    left:
      - text: Home
        href: index.qmd
      - text: feidlambda
        menu:
        - text: feidlambda v0.1
          href: test.md
        - text: feidlambda v0.2
        # href: index.qmd
      # - href: test.md
      #   text: feidlambda
        
    # right:
    #   - href: index.qmd
    #     text: Home
    #   - text: Hello
    #     menu: 
    #     - about.qmd
    #     - test.md

    right:
      - icon: plugin
        href: https://twitter.com
        aria-label: feidlambda twitter


  ## SIDEBAR
  sidebar:
    style: "floating"
    border: true

    tools: 
      - icon: house-door-fill
        href: index.qmd
        # menu: 
        #   - text: github
        #     href: https://github.com
    
    contents:
      - section: "Basics"
        contents:
          - "Fitur 2021"
          - "Dynamic Array"
          - "LET"
          - "LAMBDA"
          - "Features 365"


      - section: "Basics"
        contents:
          - index.qmd
          - basics-knitr.qmd
          - basics-jupyter.qmd
      - section: "Layout"
        contents:
          - layout.qmd
          - layout-knitr.qmd
          - layout-jupyter.qmd    

  page-footer:
    right: >-
      developed by **fiako**dev. 
      built with ❤️ and [Quarto](https://quarto.org/).
    left: >-
      &copy; 2022 PT. FIAKO ENJINIRING INDONESIA. 
      <a rel="license" target="_blank" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC-BY-NC-SA 4.0</a>.

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



